import NextThemeProvider from '@/components/next-theme-provider'
import SiteFooter from '@/components/site-footer'
import SiteHeader from '@/components/site-header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

{
  /* next-themes会导致该错误：Warning: Extra attributes from the server: class,style at html
        参考方案：https://github.com/vercel/next.js/discussions/22388#discussioncomment-6329930 */
}
{
  /* 方案一：在<html>中添加`suppressHydrationWarning`用于消除警告 */
}
{
  /* 方案二：https://nextjs.org/docs/messages/react-hydration-error#solution-2-disabling-ssr-on-specific-components */
}

// const NoSSRThemeProvider = dynamic(
//   () => import('@/components/next-theme-provider'),
//   {
//     ssr: false
//   }
// )

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="" suppressHydrationWarning>
        <NextThemeProvider>
          <section className="flex flex-col min-h-screen mx-auto max-w-5xl pt-12 pb-8 px-8">
            <SiteHeader />
            <main className="flex-1">{children}</main>
            <SiteFooter />
          </section>
        </NextThemeProvider>
      </body>
    </html>
  )
}
